apply plugin: 'com.android.application'

android {
    namespace = "com.app"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.app"
        minSdk = 21
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"
    }

    buildTypes {
        release {
            minifyEnabled = false
        }
    }
}

dependencies {
    implementation 'org.mozilla.geckoview:geckoview:151.0.20260601110758'
}
